run build for different platforms on different runners

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -3,8 +3,9 @@ on:
   workflow_call:
     inputs:
       image:
-        required: true
+        required: false
         type: string
+        default: ""
       build-args:
         required: false
         type: string
@@ -17,47 +18,148 @@ on:
         required: false
         type: string
         default: ""
+      runners:
+        required: false
+        type: string
+        default: '["ubuntu-24.04", "ubuntu-24.04-arm"]'
 jobs:
-  build-push-ar:
-    runs-on: ubuntu-24.04
+  build:
+    strategy:
+      matrix:
+        runner: ${{ fromJSON(inputs.runners) }}
+    name: build-${{ matrix.runner }}
+    runs-on: ${{ matrix.runner }}
     timeout-minutes: 15
-    permissions:
-      contents: read
-      id-token: write
+    outputs:
+      image-tag: ${{ steps.record-tag.outputs.tag }}
     steps:
-    - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4
+      - name: validate input
+        run: |
+          regex='^([A-Za-z.\/\-]+)?$'
+          if [[ "${{ inputs.image }}" =~ $regex ]]; then
+            echo "Valid docker image name"
+          else
+            echo "Invalid docker image name"
+            exit 1
+          fi
+          if [[ "${{ inputs.context }}" =~ $regex ]]; then
+            echo "Valid docker context"
+          else
+            echo "Invalid docker context"
+            exit 1
+          fi
 
-    - name: Extract branch name as docker tag
-      shell: bash
-      run: |-
-        BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^a-zA-Z0-9._-]//g' | awk '{print substr($0, length($0)-120)}')
-        if [ "$BRANCH" = "main" ] && [ "${{ inputs.tag }}" != "" ]; then
-          BRANCH="${{ inputs.tag }}"
-        fi
-        echo "branch=$BRANCH" >> $GITHUB_OUTPUT
-      id: extract_branch
+      - name: ghcr Login
+        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    - id: 'auth'
-      name: 'Authenticate to Google Cloud'
-      uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2
-      with:
-        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
-        create_credentials_file: true
-        service_account: ${{ secrets.GSA }}
-        token_format: 'access_token'
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
 
-    - uses: 'docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772' # v3
-      name: 'Docker login'
-      with:
-        registry: 'us-docker.pkg.dev'
-        username: 'oauth2accesstoken'
-        password: '${{ steps.auth.outputs.access_token }}'
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+        with:
+          repository: libops/actions
+          path: actions
+          sparse-checkout: |
+            ci/gha-extract-docker-vars.sh
+          sparse-checkout-cone-mode: false
 
-    - name: Build and push
-      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
-      with:
-        context: ${{ inputs.context }}
-        push: true
-        build-args: ${{ inputs.build-args }}
-        tags: |
-          us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ inputs.image }}:${{steps.extract_branch.outputs.branch}}
+      - run: ./actions/ci/gha-extract-docker-vars.sh
+        id: vars
+        env:
+          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
+          DOCKER_IMAGE: GHCR
+          TAG: ${{ inputs.tag }}
+          DOCKER_CONTEXT: ${{ inputs.context }}
+
+      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
+
+      - name: build+push GHCR
+        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
+        with:
+          context: ${{ inputs.context }}
+          push: true
+          cache-from: ${{ steps.vars.outputs.cache-from }}
+          cache-to: ${{ steps.vars.outputs.cache-to }}
+          tags: |
+            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.platform }}
+
+      - name: record image tag
+        id: record-tag
+        run: |
+          echo "tag=${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.platform }}" >> $GITHUB_OUTPUT
+  merge:
+    runs-on: ubuntu-24.04
+    needs:
+      - build
+    steps:
+      - name: ghcr Login
+        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - id: "auth"
+        name: "Authenticate to Google Cloud"
+        uses: "google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f" # v2
+        with:
+          workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
+          create_credentials_file: true
+          service_account: ${{ secrets.GSA }}
+          token_format: "access_token"
+
+      - uses: "docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772" # v3
+        name: "GAR login"
+        with:
+          registry: "us-docker.pkg.dev"
+          username: "oauth2accesstoken"
+          password: "${{ steps.auth.outputs.access_token }}"
+
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+        with:
+          repository: libops/actions
+          path: actions
+          sparse-checkout: |
+            ci/gha-extract-docker-vars.sh
+          sparse-checkout-cone-mode: false
+
+      - run: ./actions/ci/gha-extract-docker-vars.sh
+        id: vars
+        env:
+          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
+          DOCKER_IMAGE: ${{ inputs.image }}
+          TAG: ${{ inputs.tag }}
+          DOCKER_CONTEXT: ${{ inputs.context }}
+
+      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
+
+      - name: merge platform images
+        run: |
+          tags=""
+          mapfile -t runners < <(echo '${{ inputs.runners }}' | jq -r '.[]')
+          for runner in "${runners[@]}"; do
+            RUNNER_ARCH="X64"
+            if [[ "$runner" == *"arm"* ]]; then
+              RUNNER_ARCH="ARM64"
+            fi
+            DOCKER_IMAGE=GHCR GITHUB_OUTPUT=/tmp/vars_${runner}.txt ./actions/ci/gha-extract-docker-vars.sh
+            image=$(grep "^image=" /tmp/vars_${runner}.txt | cut -d'=' -f2)
+            tag=$(grep "^tag=" /tmp/vars_${runner}.txt | cut -d'=' -f2)
+            platform=$(grep "^platform=" /tmp/vars_${runner}.txt | cut -d'=' -f2)
+
+            tags="$tags ${image}:${tag}-${platform}"
+          done
+
+          echo "$tags"
+
+          docker buildx imagetools create \
+            -t "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}" \
+            $tags
+        env:
+          DOCKER_IMAGE: ${{ steps.vars.outputs.image }}
+          TAG: ${{ steps.vars.outputs.tag }}
+          DOCKER_CONTEXT: ${{ inputs.context }}
+          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
